### ISSUE TITLE
CocoaPods 1.0.1 break

### ISSUE THREAD

**Issue by mgoovaer** [pivotal/PivotalCoreKit#191]
![screen shot 2016-06-03 at 1 34 39 pm](https://cloud.githubusercontent.com/assets/3597484/15787538/fe7d3dae-2990-11e6-9050-0e57139cefcd.png)
![screen shot 2016-06-03 at 1 34 56 pm](https://cloud.githubusercontent.com/assets/3597484/15787539/fe7e7ebc-2990-11e6-8cbf-22dc4f670a79.png)
![screen shot 2016-06-03 at 1 35 16 pm](https://cloud.githubusercontent.com/assets/3597484/15787540/fe855462-2990-11e6-9922-c95140ba0d8b.png)

Pod installs have worked for us using CocoaPods .39. Lately we tried updating to CocoaPods 1.0.1 and encountered an issue trying to do a pod install. Appears a pivotal core kit reference creates too long of a path causing an "ERRNO:ENAMETOOLONG" error as shown in bottom of picture 'Screen Shot 2016-06-03 at 1.34.56 PM'

**Comment by briancroom** [comment]
This appears to be a Cocoapods problem, wherein it generates a very long directory name consisting of all the PCK subspecs that are being installed. Do you think you could file an issue with Cocoapods describing this?

**Comment by lalunamel** [comment]
@tjarratt looks like this can be closed

CocoaPods issue: https://github.com/CocoaPods/CocoaPods/issues/5491
CocoaPods fix: https://github.com/CocoaPods/CocoaPods/pull/5608

The fix was merged into CocoaPods master, but they haven't cut another release with that fix in it (as of the time of writing).

**To Fix - As of Aug 11 2016**
Install a version of CocoaPods based on a commit made after the fix was merged into master.
E.g., for me, using a Gemfile, I replaced

 `gem 'cocoapods'` 

with

 `gem 'cocoapods', :git => 'git@github.com:CocoaPods/CocoaPods.git', :ref => '909f1651b7076fd1459dfa67fec25ebe9a060e21'`

**Comment by tjarratt** [comment]
Thanks for doing this investigation, @lalunamel -- I agree, this can be closed now.

Long live cocoapods!
